language: node_js
node_js:
- stable
- '11'
- '10'
script: yarn test
sudo: false
cache: yarn
notifications:
  email: false
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: g4s6sV9kU1/eD41mNxBwKlTMhhQaq+b0VmeDGKY3K+2Y0R8GGYvlfm3QAx2sahzFZMFPIwK1Z+CZIcd4qeEY13+bvbf97RHg/JNMbmbEdfgExQtFs5RhgUvuoKKiHZBJs+RF2QGMuNh6w++QSeiQigTGmjcJlo9HXQbltctuSqB16u0oI3z5pDgKJVvxdMCFtJOsrVsxTfHxkPVYJRlsQ/MxeHQ75e19TfFaIdtrg0EdkL74WJ7i9BNxo41eyhSXcVqRXCNaiPx2mCRP8sSCPEaLmWC9WmRfvap/ChcEprsIKO+ftWBo7qHymiXiEPmd6R0Xqw0Yru/p/ZgltJKu5Jww9pnue5QPvYcs10nQaKeGul10PDslmxNaPqxYgeVUZ91aK1nas9M4OUOi+wZYwQ80gWWHOiWTqXQ0XAsR/Qxm+NLIiNDWqARbCP4b9YLJxIbkHGPEkYfVygJigMTdOmEy9g+jAIcEvyc6I6ZYVlYW38V9X7bhfkL4mAOyXnpoUYn3Rhnjw07ABLgRZUyhfmwGFIUmk14G0Jglk95KjfBdg40cdI3noEeIr4AdqxnORg0OkGX7L7iYe9q6hYaxshD/SBok2gmJzzDj44KuIlpN4EJdjtsvMLtJ2bk81ZpTG0wA6AxBC8hwYf7KLRKSZxsBQdd7Jbksk+Paq2IVb5g=
